services:
  # Development service
  frontend-dev:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3000:5173"
    profiles: ["dev"]

  # Production service
  frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postpilot-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    profiles: ["prod"]
